USE NEXUS_DW
GO

CREATE OR ALTER FUNCTION YIN.sfStringCompare(@StringCompare0 VARCHAR(500), @StringCompare1 VARCHAR(500), @StringCompare2 VARCHAR(500)) RETURNS INT AS

BEGIN
   DECLARE @i INT = 1
   DECLARE @Output INT = 0
   DECLARE @x VARCHAR(1)
   DECLARE @StringLength INT = LEN(@StringCompare0)

   WHILE @i <= @StringLength
   BEGIN
      SET @x = SUBSTRING(@StringCompare0,@i,1)
      IF CHARINDEX(@x, @StringCompare1 COLLATE LATIN1_GENERAL_CS_AS) > 0 AND CHARINDEX(@x, @StringCompare2 COLLATE LATIN1_GENERAL_CS_AS) > 0
      BEGIN
         SELECT @Output = CASE WHEN ascii(@x) < 97 THEN ascii(@x) - ascii('A') + 27 ELSE ascii(@x) - ascii('a') + 1 END
         RETURN @Output
      END
      SET @i = @i + 1
   END
   RETURN @Output
END
GO

WITH MY_BLAH AS (
SELECT 'PcPlnShmrLmBnmcwBhrmcmbHNGFGpwdFFwGNjNbGqNHH' Blah UNION ALL
SELECT 'tzQfRJfWZZztWzVtCTfRzFZjpFjNZjGLHbdHLDdjpb' Blah UNION ALL
SELECT 'CCQTzRLzvQVVfRzJfMPsnBlglgPmBgPmvSrl' Blah UNION ALL
SELECT 'RMfvbbszHTsssFPzDQPggpQJPQ' Blah UNION ALL
SELECT 'NSNcqVtLVGgDlpQBClVB' Blah UNION ALL
SELECT 'hmStGNNLhjNrpWLGSjWrZssbZTMMvTfMnThbRRTs' Blah UNION ALL
SELECT 'fTrTPGTbfftWBBmLjrJL' Blah UNION ALL
SELECT 'DqHwVMqVplDslmlZmpHVwNnShWZFdBBdjWBtWtdtWJSSLS' Blah UNION ALL
SELECT 'MNslpDvVHlwsmpQRgQgCfTTcvcRQ' Blah UNION ALL
SELECT 'pBBhRgDsMsswprBhvgRglZtFGFFRqZtZmRtNqtZPPN' Blah UNION ALL
SELECT 'TdmmzzmdZdqdGFtF' Blah UNION ALL
SELECT 'nmSccCVmSCpDCswMwl' Blah UNION ALL
SELECT 'NptqDsQtDTQzCvlzCpRlRp' Blah UNION ALL
SELECT 'jmZcndmjbZcjrmDvFMFFlwCvzFnF' Blah UNION ALL
SELECT 'jjgLVLrGcdDBNhWQTgHg' Blah UNION ALL
SELECT 'mLVhhfSMSTmMwClHGdpjDHjGdV' Blah UNION ALL
SELECT 'zPrZgJCgbsnrPtZzsCsbpRDjBRHnjGDRldRHppcG' Blah UNION ALL
SELECT 'JJrbsFrZqrgWbbqbrgWzJPNTwhTNCmmvfWCShhhmwwfm' Blah UNION ALL
SELECT 'ftgfljvgfgBTNvtggFDDGLGRDnMDzcQzncGt' Blah UNION ALL
SELECT 'VdbpbVdZwdwrsVVLRrMrDLDBGnBGcM' Blah UNION ALL
SELECT 'wmpWwWsHWBCCCPPvjvmSqlfTTmSNgN' Blah UNION ALL
SELECT 'jSqmzmmSSDRjLMLDwqjNcMMLTTflffWCCsRsTHnHVrfHWTsr' Blah UNION ALL
SELECT 'tdbgZpgBPdgGZGGFTHVpCsCVfVsJpnWl' Blah UNION ALL
SELECT 'FnPQFvbvhFFFbvBwScjhzcqSLLSzSN' Blah UNION ALL
SELECT 'bWdgrWwwFWbgzFWzrmNbdPqttChMSRnmqSPSnqtMRM' Blah UNION ALL
SELECT 'lcPJLDDPPfpMBCRJBtQtMh' Blah UNION ALL
SELECT 'lGDGjTGLLDHPPGjlPTsswsbHNFsNrFNFsrzr' Blah UNION ALL
SELECT 'VmtHfVhBLHVtlhphjZMdnQQZZqZmQDdzQQ' Blah UNION ALL
SELECT 'CPFwPWrvWgrfNgFPCMqZzMDDbznFTqqzDQ' Blah UNION ALL
SELECT 'NNPsfffPCsBLjpVltV' Blah UNION ALL
SELECT 'ssdBBJqJhlTJLsjTJqFFmnmmnnrcmpprmmmPcRlf' Blah UNION ALL
SELECT 'gqtqzSgWQWqmnRPPcNmmQM' Blah UNION ALL
SELECT 'GqbSVtGzvgvgWbZjjBhTdhBsTZBJBZ' Blah UNION ALL
SELECT 'jhNBsPDzLjsVhLSNzgvcvbcwbBWFcgtWCc' Blah UNION ALL
SELECT 'ZQQTTHHnGpMtnpdHpQJfMgrvWWFqbcWWGgrgwCCwwF' Blah UNION ALL
SELECT 'nHpmMnQQMmHpRnHRmMJnnTShPzljzjSNmSDhLsNSPtSh' Blah UNION ALL
SELECT 'GdqnBGFdlqzFnwdSCQZjZLLDZjZRvZLDVvgQ' Blah UNION ALL
SELECT 'PsptsTcftMfcTfhTghVDvvjnRNjVZnvV' Blah UNION ALL
SELECT 'WtPfJTfftJcMTrMnpccFwlCSCGFGCbCwJSbqBl' Blah UNION ALL
SELECT 'GjFLGhjRwFjNSjSdJCBBdQJddbBc' Blah UNION ALL
SELECT 'MVvMMHRzVtHlvlcQBQJHqdpQqCBC' Blah UNION ALL
SELECT 'vDgVztvvmrgrVRrMmsrsmZzZnWhGnNhGWTLfnLwTLhLTjngL' Blah UNION ALL
SELECT 'VljjQJSsrjjrCglsCjsgjVVfDLdZGMdvvGdQMzmvzcDQMc' Blah UNION ALL
SELECT 'HqPBtcpRWwtHbbFwBHZfmfpDfvffDfMfmGvM' Blah UNION ALL
SELECT 'PwHNbcwtqFqnwtNNqPNPPWBTThjhhVTCSJTThssVnSlJJV' Blah UNION ALL
SELECT 'GCccNCrrnCrpnzrnCDPcDDrvHHTBqTPhswqhPTBTTwBhTj' Blah UNION ALL
SELECT 'VfNmRtZgWWHdBdswdjZv' Blah UNION ALL
SELECT 'SmtQfgNmVFgVLVLVmrnMpcDLGCGLGDMpCp' Blah UNION ALL
SELECT 'CrdZdZmPPjrQdRPRDqDLBqBLBSWgWgLDzF' Blah UNION ALL
SELECT 'sQhTNphsVbhhhMJfhNVGqltVSzSllBzStlzFFFWB' Blah UNION ALL
SELECT 'hsMpwQhNMZmPmrwHRj' Blah UNION ALL
SELECT 'cNVpSVRpLHRLsVWWfnfsCshW' Blah UNION ALL
SELECT 'jvqjTgqZPlJZmbPPfbpswsPb' Blah UNION ALL
SELECT 'vlqdTZdtJvqdZjgqZrtRpQFtLFRQczHGzt' Blah UNION ALL
SELECT 'JJQndVQnQgTfNvGf' Blah UNION ALL
SELECT 'ljpbWbmNbDlGTvggGvZf' Blah UNION ALL
SELECT 'mpmRbMmmNDFDmScpzCsdzrnJrsCzrrnM' Blah UNION ALL
SELECT 'tNFtNFFzzjjzjBtVNZVbjZGlpSvTllpWwvnBlWGGBGCC' Blah UNION ALL
SELECT 'fPdcrrgPHrHMMMWlppGJSPwGSnGv' Blah UNION ALL
SELECT 'fmrqrhhfhdRddHrhQqQrfnLZjLtNttZjjRtzjFtRNj' Blah UNION ALL
SELECT 'sphRcpQRhfmnmfpptg' Blah UNION ALL
SELECT 'WVPlGLlSjCjSlGSHJJWZdmbmfvPmmnftbbgDdt' Blah UNION ALL
SELECT 'LJjjqVNjlnCTRcRhhsNcFF' Blah UNION ALL
SELECT 'vwwqttFjwgClRNCCvGNmZZMmJsPJjJpTdMpsZd' Blah UNION ALL
SELECT 'fBLVHHHrFnhHhnrVSTmfdPdPccTTPsMfsJ' Blah UNION ALL
SELECT 'QzVWzznzFbWNGNlt' Blah UNION ALL
SELECT 'vjMddVVmnWpdMndjvhhWfNLpfBsfLLZLBBSqqTZq' Blah UNION ALL
SELECT 'RFlrzQJPSRGzzzzgBZNsgBZTBflfgf' Blah UNION ALL
SELECT 'cQFDRHFDDGCJShCnvwVnnhCn' Blah UNION ALL
SELECT 'hgjlpRRLlPJJhTLJMDnwBndSPBNvMqnN' Blah UNION ALL
SELECT 'FGWVfZsmCbmVzrvtwCSMtMdnDMCw' Blah UNION ALL
SELECT 'VsVmVZfVQDmVFrrmzmGrHHTJgJjhHJcllglLQJRL' Blah UNION ALL
SELECT 'rrTVcTBgsjTffmfWHZTv' Blah UNION ALL
SELECT 'JLdnDlpGlGSLlpwJpHZfFvRZnWzWrHWqFH' Blah UNION ALL
SELECT 'wQDpDrdSlSCblCdwdSLlwQGBthPMsghNsVNVtCNNhNPjhs' Blah UNION ALL
SELECT 'CtCMvNhDMHfDDdffqtDtCflpJlBpvmWWJWwlpwFFvjwB' Blah UNION ALL
SELECT 'rGSbVGZrSsFJjlmBFZWp' Blah UNION ALL
SELECT 'rbbQgzVGrFVSPPGqfhftfqztNtqHtt' Blah UNION ALL
SELECT 'lMGZCGphllZDNshNNmHHND' Blah UNION ALL
SELECT 'PLwjVwJVsHmRrZZw' Blah UNION ALL
SELECT 'ffSdzjfZSjtjSjLtLLFFFGqFzznCpCnCBblQ' Blah UNION ALL
SELECT 'CqRnlzHCRWTlHPTZVQrcQtFsQFTcrQ' Blah UNION ALL
SELECT 'DfJcdBDBcftQjsrsBtjZ' Blah UNION ALL
SELECT 'JDfdGhSvNGhNfffGSfRznPvcRWcqCqmlvlcn' Blah UNION ALL
SELECT 'JPhBBBQCnCJCMhnhMZRrRZgbDgrWrNbglDgR' Blah UNION ALL
SELECT 'jLtSTwtsShwRNpRWrh' Blah UNION ALL
SELECT 'FLLSHsjGLGczvfPfJdfhddnHPC' Blah UNION ALL
SELECT 'BjHBNrWmTjFgJngbJhWd' Blah UNION ALL
SELECT 'vsGttMDtwCMQCJnqqqFJsggqdg' Blah UNION ALL
SELECT 'GFtDSwwMpTrzSSfcfm' Blah UNION ALL
SELECT 'rnWDQvpwWpDDcPjFPPHZjVDZ' Blah UNION ALL
SELECT 'CTJCRmCJcZZZHCCQ' Blah UNION ALL
SELECT 'LdlmdQJNpnLWbrfL' Blah UNION ALL
SELECT 'VdTdcVTZwCRGVGGMVmttlF' Blah UNION ALL
SELECT 'gnrsbngfgQSpBfpMBBBpSgMNNJbmGmlqGDqDNlFFJlGNFz' Blah UNION ALL
SELECT 'gprgQhgpMMMPsrRTCdPZwCwZZCRH' Blah UNION ALL
SELECT 'cHlCVGbbWHWqRNThhcNcmh' Blah UNION ALL
SELECT 'MwQDzpwdJwpBpPDQvrhShfLTTRLfLdjfNRqS' Blah UNION ALL
SELECT 'JwMBBrPsPDwQMDPPBPQJwMrvWHFbHHlgbsGnnWHnFnRGlblF' Blah UNION ALL
SELECT 'PQPjPDjRRQSFLSlgSmLlfh' Blah UNION ALL
SELECT 'zpLdBddbNCdqGbWJGWpJWWlsFsmmFpwfflFgfHwFhgmh' Blah UNION ALL
SELECT 'nJLdLVnzqqbjRctcPDQVTP' Blah UNION ALL
SELECT 'JdztScztPdSWLJLtgMbCjhvlbPRbjbMvCh' Blah UNION ALL
SELECT 'VZrqfQcFQwGVVFqfrTFTNqhljRHDMvMMGhRDRRHGbDhG' Blah UNION ALL
SELECT 'NZQNVQQpQmrZFQQFwQQVVZgBszJJgznstnmtcztdBSgs' Blah UNION ALL
SELECT 'nFHLNJzFbLJGGLMlTTRZbZRhWRTr' Blah UNION ALL
SELECT 'wVmgBBmtmwlqlWTwTM' Blah UNION ALL
SELECT 'sdvmgcPsCPPQQSMz' Blah UNION ALL
SELECT 'SccCqmQmgBmppLQmpSMjjlJzzsNPMDRbPNPlJM' Blah UNION ALL
SELECT 'VHZvwtZwhZHtdTwrVbNsljlRDlJPDhzsbN' Blah UNION ALL
SELECT 'dZwftVRftmcgpBCmBf' Blah UNION ALL
SELECT 'NTTlVlgNSflqbphFFhNbFp' Blah UNION ALL
SELECT 'wmmLmjwzwbWGLjRmtZZdhZLFtQQLQBFh' Blah UNION ALL
SELECT 'RvjbMjjvMzMWbDWwvzPjvmWSfVfsTlVVPVgTgPfVsnnnsJ' Blah UNION ALL
SELECT 'BsBsZHZNdWwsNdrzgCrMMqsjzzMC' Blah UNION ALL
SELECT 'flfhVWFmLrhQzCCh' Blah UNION ALL
SELECT 'fVbmFSpnSSmtnPZvdWbwvdvdHZ' Blah UNION ALL
SELECT 'NsZWWWWLsBZPhfsLmPhcFCCHCMMrqfqcvHMfHH' Blah UNION ALL
SELECT 'nThSllnplGlMpvFRcCqrrr' Blah UNION ALL
SELECT 'DnTwSztgzlDnVGTwztmdZhmLdJdNDshBdsWs' Blah UNION ALL
SELECT 'RBBGTFZGglMHvrtcgSdnNgjg' Blah UNION ALL
SELECT 'DmVcbmbJmwJDJzVVwzJfmfstnztvjnNjvNSpdptvzCnpjj' Blah UNION ALL
SELECT 'DsLcfLmbhVQssQJQscWRPBZZMMRLHFHZBGMG' Blah UNION ALL
SELECT 'FVvhVnhFnFhmvFhVcMBHLgcPClrqqrtqCppldrRRTppldg' Blah UNION ALL
SELECT 'QLWfDNwsQLtlrrCtDdpq' Blah UNION ALL
SELECT 'sJwZwLsGJWGGwzzWZNbWNLjQHSVhvHSnhcMFcbVmnvcchSBS' Blah UNION ALL
SELECT 'jTMNMrHBJWWDffRqfDBqfD' Blah UNION ALL
SELECT 'QmSFphtQqQmVmqVnPnPlpwgfnRnDPl' Blah UNION ALL
SELECT 'VqFmLFbLhmZhGFGmCmGtZLtJWzWHcJrNrHMccjMscMHzMZ' Blah UNION ALL
SELECT 'hGPGmbfPzbPfgdMdWGqBGQcqpp' Blah UNION ALL
SELECT 'nvFTvDrTdNZZlrjnMHHHpBBcppqq' Blah UNION ALL
SELECT 'rNlZZNLvRdRCRFFwZwhgbmSJPSmPfhfwhS' Blah UNION ALL
SELECT 'vjdbFWTtFRRvtvZZvdWJWbGjLhCcnrrrNqLNCPqchShNqc' Blah UNION ALL
SELECT 'QHQVlDsMfmmDMHDBdLdCSLnhNLNNfqCd' Blah UNION ALL
SELECT 'VQHsMDpHlzMBBwlsmMzmmlVwptvTWdvJdbvJtRTWgGFJJGtR' Blah UNION ALL
SELECT 'nSScBcnbbFSQVdBFBtWpwtvtPbTZthtTvT' Blah UNION ALL
SELECT 'pRzHpGjCDGzHGCGsThqqwZwPhCtvhTqZ' Blah UNION ALL
SELECT 'NzlzjDDpNldBFrlfFQ' Blah UNION ALL
SELECT 'qJlDlPPWppgppqPlplpfdvgnbMfGbdgCghMdCM' Blah UNION ALL
SELECT 'QWTWZcSsWbvVvTnhfC' Blah UNION ALL
SELECT 'tRFLwZrcrWzzlJmtBqlm' Blah UNION ALL
SELECT 'HMNMvvzzNcmfNmfbhs' Blah UNION ALL
SELECT 'qVcwCgjCLtWRSLsTPbmPfmTh' Blah UNION ALL
SELECT 'RtWCJgddWRtCJdWWgdBjwWWwpzMFpHGprcBGFFnGHQZHQGpF' Blah UNION ALL
SELECT 'gZgBDgDVGDGjmDZRtgjvVvtQdnLrcRcrdfdfCcnlscsJsn' Blah UNION ALL
SELECT 'WTqzqHqNzpHpwzNhMHNwWPbQCQcCLsnCrLLfcrffNflcNn' Blah UNION ALL
SELECT 'zHTwwpTPzTTwlFTFzwqzPbwZGgGZZBtmGGvGmBGZVFStFZ' Blah UNION ALL
SELECT 'znlSSzfzTcmmfcCt' Blah UNION ALL
SELECT 'PHWWGpqgPShPMwGwqJFTVtwtCVTCmTJcFc' Blah UNION ALL
SELECT 'qHqqSggLrRLBbvDDdndzRQ' Blah UNION ALL
SELECT 'WBddBQWZWWQqqQFMWfmrWsJnmVJJNDDVJGsLmHmLDN' Blah UNION ALL
SELECT 'PTgCjvCCPPPzSZGJVLsVZCHHnH' Blah UNION ALL
SELECT 'pzwtPTvzTjRTPtwSjPSzRgBbWMBfMwwZfbWrMrZFqFFM' Blah UNION ALL
SELECT 'BqDwVqdqlDlblQMf' Blah UNION ALL
SELECT 'ZcCWWcWzvJZjcPjZZZfTHfQJQHThqpMbQQJf' Blah UNION ALL
SELECT 'LPCcZcczZLgCjvPWgvstjsjmRRBdmGrdGdmSFGnFrtGmqr' Blah UNION ALL
SELECT 'CBvgQssVzfCBQSgvvvfmrlGrCtMGwthJlJtbrh' Blah UNION ALL
SELECT 'TpLqLRFpqdRpRTfNPtRmrMMtMlMMmlMJlt' Blah UNION ALL
SELECT 'PZTjqFFTHZZNZpqcVWzVvgzcWnSWfBDD' Blah UNION ALL
SELECT 'SVSTpgpVpdNbpcVdfjcNfbcJnqsltcJPvRJqRwQqlQsJls' Blah UNION ALL
SELECT 'zhWzDLmFHhmrWZmmzHJJQlnswqsvttrstQqs' Blah UNION ALL
SELECT 'zGtZFGGCmZmGGFhLBWBGGFdgVjgppMTSTgMfCNfVVSdj' Blah UNION ALL
SELECT 'CzjNJGcnzQJltPHttcPHTP' Blah UNION ALL
SELECT 'bLVsqLbLmSSVrqmdhVSmsVFFprfrFWrwTTWWWZpFPtlP' Blah UNION ALL
SELECT 'ssDsMqLqhvmvhdmdvzRCnQgRzzBjgnlNCM' Blah UNION ALL
SELECT 'TzTLzzSGRlRSjWzlWRzHGTpNhPhJPmdnNPPbhlbPbdhfPh' Blah UNION ALL
SELECT 'mBCDBVrCqVQvQMBcVcqBrBDsbtJfnZNbJndNNhthZNJfPZPs' Blah UNION ALL
SELECT 'wMCrqVvBzmzHTGLw' Blah UNION ALL
SELECT 'NbfwfZPPdVNPdBdQBcmQzrQz' Blah UNION ALL
SELECT 'nnWqHLWGFMDFDLDjsqnHLsrQGzmJczmQrgJmJGZmQrgJ' Blah UNION ALL
SELECT 'FFWRsHMHCZCWFwRwphpvlfTTpp' Blah UNION ALL
SELECT 'PclPlVZvLDNvVZSLSMvvDttmtfzFtzHqtqtzzccCFc' Blah UNION ALL
SELECT 'jrggQGhjQsTDbrbJjJQqzzCsdtzzFCdHqmBBHz' Blah UNION ALL
SELECT 'WGDgngwrQggZMNvMWPMRRV' Blah UNION ALL
SELECT 'wNgpMdMMcdSscccNcLLTbtQJtQJQltJwFtlBlzBt' Blah UNION ALL
SELECT 'HHGhrLrCvHWHCPhrWDtnBllnQbfQftGnfnBF' Blah UNION ALL
SELECT 'HvLjWCLHPZvHHHZjjrqVTTZVcppMgNNNNSpS' Blah UNION ALL
SELECT 'QQrwQmvWQjgTfvBjfffrSDcrqSqDDVLctqqcVd' Blah UNION ALL
SELECT 'GnHFnGhGplGMlHMNhzBzlLPLVcVNCPDqVNdcqLdqtV' Blah UNION ALL
SELECT 'GnMGpslMhGsRzzHzGsZFZQJTTmWfBbvfgfgJRfbwbW' Blah UNION ALL
SELECT 'MRCtSwMhvjCGtvMZDVWpVZJlVccNDlpb' Blah UNION ALL
SELECT 'gdLQFFwwLfHJWnQlcJJbWc' Blah UNION ALL
SELECT 'rdqdmqHLTLmsswsFHLFtMPRMCSSRtSjTPMPSCR' Blah UNION ALL
SELECT 'jmCCnLCLZjZjRjQTLZQhGPGhhzHhDRGRDzwzwh' Blah UNION ALL
SELECT 'stlJlrlJJcSSfSMMzPfhhGhzpwhpNwhD' Blah UNION ALL
SELECT 'rbrbBcSlWmdZWjDnTm' Blah UNION ALL
SELECT 'PNBRNnnqQRNfVfRtVVzgFLLttpSwgzzzmFFF' Blah UNION ALL
SELECT 'fcWlcbvvCFzLbwLw' Blah UNION ALL
SELECT 'rlrMrhTJhDcTTfhRNqHRQPQRQNQB' Blah UNION ALL
SELECT 'TrprpprRVVfpRpVqTVpzDdvmvbbCchhcttqcthSMdd' Blah UNION ALL
SELECT 'JlnZnFlsMBZnJHlsLsCLbSNtbNhdbbShCScm' Blah UNION ALL
SELECT 'FlZjjsHHsnQFQwTDzMRRpGRR' Blah UNION ALL
SELECT 'wHWzwCTTqJhzzvJhWHWhqJWrFsFQrrrFCfFfgjjgjprfsp' Blah UNION ALL
SELECT 'DBRmZRtZLbnRBGSBmtGSLpjBrrsfrgsTQVrVrrPrgr' Blah UNION ALL
SELECT 'DLnbcbtLtmNNmbRcGbcGmHzlThNNhqJTHdvqvWlHJh' Blah UNION ALL
SELECT 'GSNqjRcqflNLnCTTWrWn' Blah UNION ALL
SELECT 'BmwQtmtJwPwmzMwQtHtVssvrnpWTTnsTTgpVCLCs' Blah UNION ALL
SELECT 'DBBQHJJrzhzQDDfSljRfhccfcdZf' Blah UNION ALL
SELECT 'wtgtChCwzqgLzjggqtHtjFHHFcnPfdRDfZZVcPfVZZfGnfdm' Blah UNION ALL
SELECT 'vBTrRTTWGGmcTDVD' Blah UNION ALL
SELECT 'SJMbbpWslJblSSNzNsztRChzqRCj' Blah UNION ALL
SELECT 'gBHHCtVCSHMQlfFTQqCfmq' Blah UNION ALL
SELECT 'WrpdwjbwbwQGlPqSqblP' Blah UNION ALL
SELECT 'wWDncWrDDNdWNRjScScjpzvHZtBMZtJsvLVgvzssBsvs' Blah UNION ALL
SELECT 'VppWpVfmZPBlnmrGBzhttMzMpctLLcChSh' Blah UNION ALL
SELECT 'FwgLJvRdHcwMzSzjzc' Blah UNION ALL
SELECT 'QvbgdQLQgDvsqvqRHRDdDQDBWmBGBflnVbZmZmmnBBWrmW' Blah UNION ALL
SELECT 'SqShwLFCQGpDHCtZCWpW' Blah UNION ALL
SELECT 'bdHPHjTbJdsMnPHPbdjgtnBlVlBnVgtZpDBpWV' Blah UNION ALL
SELECT 'bdmPcjbjMNMvvHbTcQRNfRwRwLffwwqwNF' Blah UNION ALL
SELECT 'zdRHTpQTQHQnpnnQRHTsNNlJSJWmzJmJllNmSG' Blah UNION ALL
SELECT 'FBbRvLbFRwLqbbVgBVqqLFqJtJNcltsSGmgmGtNtgWmstm' Blah UNION ALL
SELECT 'FLhhfvvVwvjqfLRBqLVqbwqZQrTTpHMHjdrpnnDPDQCdCrpC' Blah UNION ALL
SELECT 'JgjzvbJCWgbjgGbJWjRhgNPGHHBMtqBStZZsHMSsBqtD' Blah UNION ALL
SELECT 'cfQdwQFdQQppnVVnlFLLBsBZMhqPlPMMqBSHDtHM' Blah UNION ALL
SELECT 'wnQhcnVddmdWgjvjmvRjjJ' Blah UNION ALL
SELECT 'QpcRtndvsLcVJtRSzWSlWjzSbjjWBv' Blah UNION ALL
SELECT 'qGZPqCTmGPqgGTCqHgCqZCPFWbbBNBMNBbdBMlWWrbjlMbFl' Blah UNION ALL
SELECT 'qhHDGhCmPhZHgDmDVQthttRchLwLdwcc' Blah UNION ALL
SELECT 'srpPMwlMmsrGFGswvDRhRWRDJJJchJ' Blah UNION ALL
SELECT 'fSgBbCBNnBTTgCNLTCRJhRJVWhTcVVVFFJdR' Blah UNION ALL
SELECT 'SbBnnLNZCLFQCZjnCnZFjPrzqmlMmmsrpzrlsmtt' Blah UNION ALL
SELECT 'BBsfDfsBDSWRwlLqmWCpWcllrl' Blah UNION ALL
SELECT 'nQMgMnnnhdntgMBrCdpNNLNlNqLqLl' Blah UNION ALL
SELECT 'FnQFHzPQJjJGRBGvfR' Blah UNION ALL
SELECT 'lRnVRFFlgMCRVwLgFZRnZQHWdcftHdmcJHmmMdzzfz' Blah UNION ALL
SELECT 'DGBqGQbhhBDbSBpGDBzqdNHJdtmcWdqdmtcm' Blah UNION ALL
SELECT 'bjbsBvjhSlVsPRgLQl' Blah UNION ALL
SELECT 'dDLbRdTMRJMbFRzZBfzNSjtNBzBD' Blah UNION ALL
SELECT 'PmgspqqVrppTVrvrsPhhfQwZBwNjNtNffzqqfwwN' Blah UNION ALL
SELECT 'mCcmsngrPvpVTssCVsvsPLRRJllGFlnRGbMJMWWlJJ' Blah UNION ALL
SELECT 'fGlGZHRRbwgPbZRRNCdcSWpncnQtQWlWcWpW' Blah UNION ALL
SELECT 'JrTLJgVvVLQQvtSvQncQ' Blah UNION ALL
SELECT 'JrrrmMTBVTmjBMrVjrshmJzgCfzRPCRZPGHfbwNPzbZHNH' Blah UNION ALL
SELECT 'qqqlDDZzVVnNqHDDFFFNlQpzjrTvsvzTbgJQQggjJp' Blah UNION ALL
SELECT 'cWPWcCmMfCMWdtPMhMbQQQjGGjpdvjTbjgjr' Blah UNION ALL
SELECT 'WtMSBCtCwchChMfBWtcPnNVNqZZLDRNqTRnnlwHn' Blah UNION ALL
SELECT 'mvQQnhBvhmvBmncmZBclTZTQccRFNFFdqFFgVqSRrgFrppNR' Blah UNION ALL
SELECT 'MjzJPzGPfffMCjVVjfPHLCFRNFStqrdRSdqdNGRqNptq' Blah UNION ALL
SELECT 'HDJHPjDJLfjbzfwPjCzCWWTwlmQhBnsWBvVsvBvZ' Blah UNION ALL
SELECT 'RVjcshhscQhrVjhvzjVfDNnzGtftmDHFttFGGf' Blah UNION ALL
SELECT 'qLcBCCMBJJbTdBDnNtdfnmDG' Blah UNION ALL
SELECT 'WpZgLLclTclRwgjgsrwsvj' Blah UNION ALL
SELECT 'shhhltNPcDtlNcNMcsctNtppLZvWWFLTFFZpTZDQgFLT' Blah UNION ALL
SELECT 'dRgJVzRHbqnLpTWQvLLJfp' Blah UNION ALL
SELECT 'mCVCdzqHndbqHCrVqRrmbwtNBsmPwNmScPgtPhBclw' Blah UNION ALL
SELECT 'bDDZMDrFPsrsMcsrbJZJdMMGpSzpSbwRSSRGpCHCGzlhCC' Blah UNION ALL
SELECT 'BWWNQjBLQVHhlGpSCmwj' Blah UNION ALL
SELECT 'ffwnNwfgtnNgVVwfNWBWnFsMJTJTcPFJcTFDsrJstJ' Blah UNION ALL
SELECT 'vQbQLQBpBvbvpHplHNTHWGZDngntZCQGgZhGhtjG' Blah UNION ALL
SELECT 'rqccPPmcrffRmsmCjVgnrGChChDjgW' Blah UNION ALL
SELECT 'fqRJsJMSlSzSWTbT' Blah UNION ALL
SELECT 'brsjjJPJwrJJsrRRlllNQGWQpwppCtfGGtWzGGMQ' Blah UNION ALL
SELECT 'ncBqqLTDnmLgVDZVnBDmdtVVtMzWWdMCQdpQWdVz' Blah UNION ALL
SELECT 'hDZgTSSnTzNPNFSFPF' Blah UNION ALL
SELECT 'VZVJJtWTsfTVVWsJhPWrCjzSBJlHSmjJCRlNSSlz' Blah UNION ALL
SELECT 'CqMpwccgvvgLnvLbMMRRjBNHzjmGmwNHlmlN' Blah UNION ALL
SELECT 'gLqqvpCDfVDrTfVW' Blah UNION ALL
SELECT 'CNMDGNPPNJCGbLnTffsTLT' Blah UNION ALL
SELECT 'tcBBRlrBdQrtmtWFjjbnrTjjFbjr' Blah UNION ALL
SELECT 'cTQQhcmvcBRcwDMVDZZPPCJh' Blah UNION ALL
SELECT 'mBCdgPLgZmLfGmfvGhtRQJWjtjQGQhtN' Blah UNION ALL
SELECT 'pMwrVwbwHMsqcTWQhQWzggTTWp' Blah UNION ALL
SELECT 'nnSMwrlrsmSZgvvmDd' Blah UNION ALL
SELECT 'WNSzpCzNzqzNdmqrRHrrLHFrJH' Blah UNION ALL
SELECT 'MtPfvnGMPnMcbnRtDHTRFFDrmJRQ' Blah UNION ALL
SELECT 'PcBsfPPHPGGfcSzZjNjpNZZdCs' Blah UNION ALL
SELECT 'mDCZVLDhWVSDCRvGtsGgGRHl' Blah UNION ALL
SELECT 'JjPwPNdcPnjPdcwNltHzzGmgGJzQJJRQ' Blah UNION ALL
SELECT 'dqfjnNmwmbmWrZMbMrThhB' Blah UNION ALL
SELECT 'qtBpNZFpBGFNfZNPmZPmQmHrmPPPTz' Blah UNION ALL
SELECT 'LLwJLvDvlWWLHdwDrVcCRcDVzzVVcV' Blah UNION ALL
SELECT 'sMMwvgjnMvjvnlsvNFBqfGHFqHGjtSpS' Blah UNION ALL
SELECT 'MmZZsFgwJTdTMdgmZdZRgFhDHhPQPPnRPhCrHhnnrPDD' Blah UNION ALL
SELECT 'fBcLlNNpQCDLDJJC' Blah UNION ALL
SELECT 'jSbWWlWpBpclWlWpNWlVBbWVdgwswFJmFJsGtdMggZFGbZwd' Blah UNION ALL
SELECT 'CMVQVMLLMFGRCMWQttnqqwQwhqsm' Blah UNION ALL
SELECT 'pJzlczSpPpPgmsqNhmPGDstq' Blah UNION ALL
SELECT 'gZgTccZGGpzdpjclGRVMVRFRMFvHRLRdLf' Blah UNION ALL
SELECT 'FMWMSBtStZqZWQtFtScWWSZmHPVJJVHwwlTgmgbzQwbwTJ' Blah UNION ALL
SELECT 'jhGLhdjNjsLvLsshzHJPVdVmmbzHzdHJ' Blah UNION ALL
SELECT 'jvDRNjnDNGRCzjLzZZpqnrFBSccWrMcB' Blah UNION ALL
SELECT 'zggmthDDghHvtrdgrVWfSBRwTHLWHwsBWw' Blah UNION ALL
SELECT 'PGGjpCjQnJQGJcJnnQpjFWVSsZWVLRZLBcsWSZBRWS' Blah UNION ALL
SELECT 'FGQlpnJCbqqGGRCjjnlCqGMtdNmmmvdNmmmzvhbrmgMz' Blah UNION ALL
SELECT 'TstvBTdgBhqTsdTcPlfCSrNMrNnrCNNSNNgp' Blah UNION ALL
SELECT 'HwLQwQDZzDjnDbmMhNSnmm' Blah UNION ALL
SELECT 'FZLVzLLQHRRzwWHjdPlJctlJtlsllhRs' Blah UNION ALL
SELECT 'fBtPsMDDswHvBmmVdBlSBRcGGnhVhg' Blah UNION ALL
SELECT 'LWJbrpFqpTLTTjqqNWlhnRGGSnhrcSdlRlsh' Blah UNION ALL
SELECT 'JWNbbpjJzTbNNNJNJMvmvfZHvzDsHDCsZw' Blah UNION ALL
SELECT 'LPGnPNLtwGhFFnJPfsqpVVszzpsP' Blah UNION ALL
SELECT 'TcWdvlrcWddggrDBDDdDMmWzRJqfVQZqmsfZsRQzZfZzQJ' Blah UNION ALL
SELECT 'TldWrMrDdlDCDdMTcwSLVCSShLNSwHjhGF' Blah UNION ALL
SELECT 'JGsWWWQsJmPwQWbBPmccbcbqFfMMpFDVCDFVFVCDqqfFwD' Blah UNION ALL
SELECT 'ZtLnlvLnNtvLndnCmfMVSmVCClfpVp' Blah UNION ALL
SELECT 'zTzZtjnZNLNmZvdtznntHHZJbBRGBRQWcJGbGsbsJRPQWT' Blah UNION ALL
SELECT 'MLmlMTPtQtMNlhbqbbqhflBB' Blah UNION ALL
SELECT 'rcrvjpSvScbRbBvbDBPG' Blah UNION ALL
SELECT 'ZZJzSHpzPrJzHFmMVMFmHCLNtV' Blah
), ADD_RN AS (
SELECT Blah, ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) RN
  FROM MY_BLAH
), RN_Position AS (
SELECT Blah, (RN+2)/3 RN_Group, RN%3 RN_Position
  FROM ADD_RN
)
SELECT SUM(NEXUS_DW.YIN.sfStringCompare([0],[1],[2])) MyPriority
  FROM RN_Position
PIVOT (MAX(Blah) FOR RN_Position IN ([0],[1],[2])) P
;
